### ISSUE TITLE
Proofreader

### ISSUE THREAD

**Issue by 1inkin** [PavelSyomin/gpzuparse#1]
Здравствуйте. Извиняюсь, что не по теме. Если Вы еще занимаетесь компонентом Proofreader, то не могли бы открыть Issues для него, чтобы можно было сообщать о проблемах?

**Comment by PavelSyomin** [comment]
Здравствуйте! Не очень активно, так как много других дел, но всё же занимаюсь. Открыл issues, попробуйте завести там тикет — постараюсь посмотреть по возможности.
